In [32]:
## Importamos librería
## Quien no la tenga, primero la instala
## python3 -m venv Entorno -- Crear Entorno
## source Entorno/bin/activate -- Activar entorno
## pip install numpy

import numpy as np

In [33]:
escalar = np.array(5)
print(escalar)

5


In [34]:
vector = np.array([5,4,2,2])
print(vector)

[5 4 2 2]


In [35]:
## Ojo acá con la dimensión ---> y en los que sigue
tensor = np.arange(12).reshape(3,2,2)
print(tensor)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [36]:
matriz = np.arange(9).reshape(3,3)
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
matriz = np.arange(4).reshape(4,1)
print(matriz)

[[0]
 [1]
 [2]
 [3]]


In [38]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
np.arange(start = 2, stop = 10, step = 2)

array([2, 4, 6, 8])

In [40]:
np.arange(11,1,-2)

array([11,  9,  7,  5,  3])

In [41]:
np.arange(11,1,-2)

array([11,  9,  7,  5,  3])

In [42]:
np.linspace(start = 11, stop = 12, num = 20)

array([11.        , 11.05263158, 11.10526316, 11.15789474, 11.21052632,
       11.26315789, 11.31578947, 11.36842105, 11.42105263, 11.47368421,
       11.52631579, 11.57894737, 11.63157895, 11.68421053, 11.73684211,
       11.78947368, 11.84210526, 11.89473684, 11.94736842, 12.        ])

In [43]:
linea = np.linspace(start = 0, stop = 1, num = 10)
linea

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [44]:
## Primero instalar matplotlib
## pip install matplotlib
## recordar que esto, de momento no es requisito saberlo, lo hicimos para entender un poco mejor la geometría
## de los datos


In [45]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
plt.plot(linea, '*')

In [ ]:
print(np.zeros(4))

In [ ]:
print(np.zeros((2,2)))

In [ ]:
print(np.ones(6))

In [ ]:
print(np.ones((3,3)))

In [ ]:
print(np.full(shape = (2,2), fill_value = 5))

In [ ]:
print(np.full(shape = (2,3,4), fill_value = 0.55))

In [ ]:
base = np.linspace(2,6,4)
print(base)
print(np.full_like(base, np.pi))

In [ ]:
help(np.linspace)

In [ ]:
randoms = (np.random.rand(100))
randoms

In [ ]:
## recordar que el bins, son las cantidad de divisiones que le pedimos al gráfico que nos haga, ejemplo: si le pasamos
## bins = 1, va a ser sólo un rectángulo...
plt.figure("random")
n, bins, patches = plt.hist(randoms, bins=100, facecolor='green', alpha=0.75)  
plt.show()

In [ ]:
uniformes = np.random.uniform(low = 0, high = 20, size = 10000)
print(uniformes)

In [ ]:
plt.figure("uniformes")
n, bins, patches = plt.hist(uniformes, bins=100, facecolor='green', alpha=0.75)  
plt.show()

In [ ]:
normal = np.random.randn(10)
normal

In [ ]:
normal = np.random.randn(10000)

In [ ]:
plt.figure("normal")
n, bins, patches = plt.hist(normal, bins=100, facecolor='green', alpha=0.75)  
plt.show()

In [ ]:
enteros = np.random.randint(low = 0, high = 10, size = (3,3))
enteros

In [ ]:
matrix_cool = np.arange(9).reshape(3,3)
print(matrix_cool)

In [ ]:
matrix_cool[1,2]

In [ ]:
matrix_cool[0,:]

In [ ]:
matrix_cool[:,0]

In [ ]:
a = np.array([2,4,6])
b = a

In [ ]:
b[0] = 8
b

In [ ]:
a

In [ ]:
np.arange(8).reshape(2,2,2)

In [ ]:
A = np.arange(5,11)
A

In [ ]:
A + 10

In [ ]:
## Operaciones con listas ---> Diferencias con los arrays de Numpy
a = [1,2,3,4]
b = [4,5,8,14]
def restlistas(a,b):
    resta=[]
    for i in range(len(a)):
        resta.append(a[i]-b[i])
    return resta

In [ ]:
restlistas(a,b)

In [ ]:
B = np.arange(0,6)

In [ ]:
A - B

In [ ]:
a = np.array([[2,3], [2,3], [4,5]])
a.shape

In [ ]:
b = np.array([[1,6,5,2,2], [5,1,1,4,4], [1,2,4,3,5]])
b.shape

In [ ]:
## Este error lo dejo, para que se acuerden de tener en cuenta las dimensiones de las matrices y arrays.
## Lean los errores. Copien y peguen los errores en google, y algo va a salir...
a@b

In [ ]:
b = np.array([[1,6,5,2,2], [5,1,1,4,4]])
b.shape
np.matmul(a,b)

In [ ]:
mult = a@b
mult

In [ ]:
mult.T

In [ ]:
m = np.mat([(1,2,3),(4,5,6)])

In [ ]:
m.I

In [ ]:
mat = np.mat([4,5,6])


In [ ]:
mat.I

In [ ]:
height_list = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75]
print(np.mean(height_list))

In [ ]:
np.median(height_list)

In [ ]:
np.std(height_list)

In [ ]:
np.percentile(height_list, 90)

In [ ]:
## Vean la diferencia de rendimiento entre numpy y las listas... 
%%time
for i in range(100000):
    print(i)

In [ ]:
%%time
np.arange(1000000)

In [ ]:
## Diferencia entre None y Nan
a = np.array([1, None, 2 ,3])
for i in a:
    print(type(i))
a

In [ ]:
a = np.array([1, np.nan, 2 ,3])
a

In [ ]:
a = np.arange(0,20).reshape(2,10)
print(a)

### Mascaras

In [46]:
mascara = ((a%2) == 0)
mascara

NameError: name 'a' is not defined

In [ ]:
a[mascara]

In [ ]:
a

In [ ]:
a = np.arange(10,100).reshape(9,10)
a

In [ ]:
a.shape

Estudien 💪😁🙌