In [ ]:
import numpy as np

In [ ]:
#Cómo crear una matriz 1D
print(np.arange(10))

In [ ]:
# La función Python NumPy arange()se usa para crear una matriz con valores espaciados
# uniformemente dentro de un intervalo dado. Esta función toma cuatro 
# parámetros start, stop, step, dtype.
print(np.arange(3, 22, 4))
print(np.arange(start=2, stop=22, step=3))

In [ ]:
"""
numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
shape– Define la forma de la matriz que es un entero o secuencia de enteros. La forma de la nueva matriz, por ejemplo, (4, 3) o 2.
fill_value – Valor para completar la matriz.
dtype– Es un parámetro opcional que especifica el tipo de datos de la matriz devuelta.
order– {'C', 'F'}, opcional: Para almacenar datos multidimensionales en orden/patrón de fila principal (C) o columna principal (F) en la ubicación de la memoria.
like– el valor debe ser similar a una matriz, opcional
"""

#Cómo crear una matriz booleana
print(np.full((3, 3), True, dtype=bool))
#Cómo crear una matriz 
print(np.full((4, 3), 7))
print(np.full(6,4))
print(np.full((4,3),'2',dtype=str))
print(np.full((3,4),'3.2',dtype=float))

In [ ]:
#Cómo extraer elementos que satisfacen una condición dada de la matriz 1D

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Extraiga todos los números impares
print([arr % 2 == 1])
print(arr[arr % 2 == 1])
#Extraiga todos los números impares
print(arr[arr % 2 == 0])

#Cómo reemplazar elementos que satisfacen una condición con otro valor en una matriz numpy
# Extrae el dato desde el primero hasta el final: por ejemplo
# y va asignando los nuevos valores
arr[arr % 2 == 1] = -1
arr


In [ ]:
# La función Python NumPy where() se usa para devolver los índices de los elementos 
# en una matriz de entrada donde se cumple la condición dada.
#numpy.where(condition, [x, y, ])
"""
    condition-Cuando es verdadero, produce x, de lo contrario, produce y.
    
    x,y: Valores entre los que elegir. x, y, y la condición deben poder 
    transmitirse a alguna forma.
"""
arr = np.arange(10)
print(np.where(arr > 7))
print(np.where(arr > 7, 1, 3))
print(np.where(arr > 7, 5, arr))
print(np.where((arr > 3) & (arr < 8), -2, 150))

In [ ]:
#Cómo reemplazar elementos que satisfacen una condición sin afectar la matriz original
arr = np.arange(10) # Crea array del o al 9
out = np.where(arr % 2 == 1, -1, arr)
print(arr) #> [0 1 2 3 4 5 6 7 8 9]
print(out)

In [ ]:
# El método de matriz Python NumPy reshape()se usa para cambiar la 
# forma de la matriz NumPy sin cambiar sus datos.

    #numpy.reshape(array, newshape, order='C')
"""
    array – La matriz a reformar, puede ser una matriz NumPy de cualquier forma o 
    una lista o lista de listas.
    
    newshape – La nueva forma debe ser compatible con la forma original, puede ser una 
    tupla o un int. Para convertir la forma de matrices 2D o 3D, debe pasar una tupla. 
    Para crear una matriz de forma 1D, se debe pasar un número entero.
    
    order – {'C', 'F', 'A'}, opcional para leer los elementos de a usando este orden de 
    índice. 'C' significa leer/escribir los elementos utilizando un orden de índice 
    similar a C. 'F': Leer elementos de la columna de la matriz, es decir, utilizando 
    un orden de índice similar a Fortran. 'A': Leer elementos de la matriz en función 
    del orden de memoria de los elementos.
"""
arr = np.arange(10)
print(np.reshape(arr, (-1, 2)))
arr = np.array([2, 4, 7, 9, 13, 16, 20, 24, 27, 29, 33, 35]) # Array
arr2 = arr.reshape(4, 3) # de 1D a 2D
print(arr2)
arr2 = np.reshape(arr, (2, 2, 3)) # de 1D a 3D
print(arr2)
arr2 = np.reshape(arr, (2, 6), order='F')
print(arr2)
arr2 = np.reshape(arr, (4, 3), order = 'C')
print(arr2)

In [ ]:
# Cómo remodelar una matriz
arr = np.arange(10)
arr.reshape(2, -1)

In [ ]:
# La función Python NumPy repeat()se usa para repetir los elementos individuales 
# de una matriz un número específico de veces.

# numpy.repeat(arr, repeats, axis=None)
"""
    arr– Matriz de entrada.

    repeats– Int o matriz de tipo int. Define el número de repeticiones para cada elemento. 
    las repeticiones se transmiten para adaptarse a la forma del eje dado.

    axis– Qué valores se repiten junto con el eje especificado. De forma predeterminada, 
    toma la matriz de entrada aplanada y devuelve una matriz de salida aplanada. Puede ser 0 y 1.

    Returns value – Matriz de salida que tiene la misma forma que arr, excepto a lo 
    largo del eje dado.
"""
arr = np.array([5,7,9,11,13,19])
arr2 = np.repeat(arr, 2)
print(arr2)

arr = np.array([[15,28,57],[99,65,34],[37,55,88]])
arr2 = np.repeat(arr, 2)
print(arr2)

In [ ]:
# Puede usar la función Python NumPy concatenate() para unir una secuencia de matrices 
# a lo largo de un eje (fila/columna). Esta función se utiliza para unir dos o más matrices 
# de la misma forma a lo largo de un eje específico.

    #numpy.concatenate((arr, arr1, ...), axis=0, out=None)
"""
    arr,arr1: una secuencia de array_like. Las matrices deben tener la misma forma, 
    excepto en la dimensión correspondiente al eje (la primera, por defecto).
    
    axis: El eje a lo largo del cual se unirán las matrices. Si el eje es Ninguno, 
    las matrices se aplanan antes de su uso. El valor predeterminado es 0.
    
    out: Si se proporciona, el destino para colocar el resultado.
    
    Returns: La matriz concatenada.
"""

arr = np.array([[4, 6], [9, 13]])
print(arr)
arr1 = np.array([[8, 3], [12, 19]])
print(arr1)

print("*"*20+" SOLUCIÓN "+"*"*20)
con = np.concatenate((arr, arr1))
print(con)

#Use Unir las dos matrices a lo largo del eje = 1
print("*"*20+" SOLUCIÓN "+"*"*20)
print("Use Unir las dos matrices a lo largo del eje = 1")
con = np.concatenate((arr, arr1), axis = 1)
print(con)

In [ ]:
# Cómo apilar dos matrices verticalmente
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(8, 10).reshape(2,-1)
print(b)
print("*"*20+" SOLUCIÓN "+"*"*20)
print("*"*5+" A "+"*"*5)
print(np.concatenate([a, b], axis=0))
print("*"*5+" B "+"*"*5)
print(np.vstack([a, b]))
print("*"*5+" C "+"*"*5)
print(np.r_[a, b])


In [ ]:
#Cómo apilar dos matrices horizontalmente
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(8, 10).reshape(2,-1)
print(b)
print("*"*20+" SOLUCIÓN "+"*"*20)
print("*"*5+" A "+"*"*5)
print(np.concatenate([a, b], axis=1))

In [ ]:
# La función NumPy tile()en Python se usa para construir una matriz repitiendo una matriz 
# de entrada dada por un número específico de veces dado por el repsparámetro. 
# La np.tile()función NumPy toma una matriz como entrada y crea una nueva matriz 
# repitiendo la matriz de entrada.

    #numpy.tile(arr, reps)
"""
    arr:Este parámetro representa la matriz de entrada.
    reps:El número de repeticiones de arr a lo largo de cada eje.
"""
arr = np.array([2, 5, 8])
print(arr)

arr2 = np.tile(arr, reps=8)
print("*"*20+" SOLUCIÓN "+"*"*20)
print(arr2)

arr2 = np.tile(arr, (4,3))
print("*"*20+" SOLUCIÓN "+"*"*20)
print(arr2)

#Use la función NumPy tile() para una matriz bidimensional
arr = np.array([[2, 5, 8],[0, 4, 7]])
repetitions = (3,2)
arr2 = np.tile(arr, repetitions)
print("*"*20+" SOLUCIÓN "+"*"*20)
print(arr)
print(arr2)

In [ ]:
#Cómo generar secuencias personalizadas en numpy sin codificación dura
a = np.array([1,2,3])
print("*"*20+" SOLUCIÓN "+"*"*20)
np.r_[np.repeat(a, 3), np.tile(a, 3)]

In [ ]:
# Cómo obtener los elementos comunes entre dos matrices de python numpy
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print("*"*20+" SOLUCIÓN "+"*"*20)
np.intersect1d(a,b)

In [ ]:
# Cómo eliminar de una matriz los elementos que existen en otra
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print("*"*20+" SOLUCIÓN "+"*"*20)
np.setdiff1d(a,b)

In [ ]:
# Cómo obtener las posiciones donde coinciden los elementos de dos matrices
a = np.array([1,2,3,2,3,4,3,4,5,6,8])
b = np.array([7,2,10,2,7,4,9,4,9,8,8])

print("*"*20+" SOLUCIÓN "+"*"*20)
np.where(a == b)

In [ ]:
# Cómo extraer todos los números entre un rango dado de una matriz numpy
a = np.array([2, 6, 1, 9, 10, 3, 27])

print("*"*20+" SOLUCIÓN "+"*"*20)
index = np.where((a >= 5) & (a <= 10))
print(a[index])
index = np.where(np.logical_and(a>=5, a<=10))
print(a[index])
print(a[(a >= 5) & (a <= 10)])

In [ ]:
# Cómo hacer una función de python que maneja escalares para trabajar en matrices numpy
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

In [ ]:
# Cómo intercambiar dos columnas en una matriz 2d numpy
arr = np.arange(9).reshape(3,3)
print(arr)

print("*"*20+" SOLUCIÓN "+"*"*20)
arr[:, [2,0,1]]

In [ ]:
# Cómo intercambiar dos filas en una matriz 2d numpy
arr = np.arange(9).reshape(3,3)
print(arr)

print("*"*20+" SOLUCIÓN "+"*"*20)
arr[[1,0,2], :]

In [ ]:
# Cómo invertir las filas de una matriz 2D
arr = np.arange(9).reshape(3,3)
print(arr)

print("*"*20+" SOLUCIÓN "+"*"*20)
arr[::-1]

In [ ]:
# Cómo invertir las columnas de una matriz 2D
arr = np.arange(9).reshape(3,3)
print(arr)

print("*"*20+" SOLUCIÓN "+"*"*20)
arr[:, ::-1]

In [ ]:
# La función NumPy random.randint() en Python se usa para devolver enteros aleatorios 
# de los valores especificados con parámetro bajo  (inclusivo) a  alto  (exclusivo). 
# Crea una matriz de una forma dada y la llena con números enteros aleatorios desde 
# bajo (inclusivo) hasta alto (exclusivo).

    # random.randint(low, high=None, size=None, dtype=int)
"""
    low– Números enteros (con signo) más bajos, obtener de la distribución. 
    Todos los números generados usando randint() son mayores o iguales a low.
    
    high– Los enteros más grandes (con signo), se obtienen de la distribución. 
    Es el límite superior. Todos los números generados a partir de randint()son 
    menores que high.
    
    size– Número entero o tupla de números enteros. Usando esto para especificar el 
    tamaño o la dimensión de la matriz. Por ejemplo, size=(3,4)llena una matriz de 
    tres filas y cuatro columnas con números enteros.
    
    dtype– Tipo de resultado deseado.
"""
arr = np.random.randint(low=1, high=6, size = 8)
print("*"*20+" SOLUCIÓN "+"*"*20)
print(arr)
print("\n")

# Genere una matriz 2-D de enteros aleatorios
arr = np.random.randint(low=1, high=9, size=(2, 4))
print("*"*20+" SOLUCIÓN "+"*"*20)
print(arr)
print("\n")

# Genere una matriz 2-D de enteros aleatorios
arr = np.random.randint(low=3, high=8, size=(2, 3, 4))
print("*"*20+" SOLUCIÓN "+"*"*20)
print(arr)

In [ ]:
# Cómo crear una matriz 2D que contenga flotadores aleatorios entre 5 y 10
arr = np.arange(9).reshape(3,3)
print(arr)

print("*"*20+" SOLUCIÓN "+"*"*20)
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

In [ ]:
# Cómo imprimir solo 2 decimales en la matriz python numpy
rand_arr = np.random.random((5,4))
print(rand_arr)

print("*"*20+" SOLUCIÓN "+"*"*20)
np.set_printoptions(precision=2)
rand_arr[:4]

In [ ]:
# Cómo imprimir bonitas una matriz numpy suprimiendo la notación científica ( como 1e10
np.set_printoptions(suppress=False)

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

print("*"*20+" SOLUCIÓN "+"*"*20)
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

In [75]:
# Cómo limitar el número de artículos impresos en la salida de la matriz numpy
np.set_printoptions(threshold=6)
a = np.arange(25)
print(a)

[ 0  1  2 ... 22 23 24]


In [79]:
# Cómo importar un conjunto de datos con números y textos que mantienen el texto intacto en python numpy
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris.shape)

iris[:4]

(150, 5)


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa']], dtype=object)

In [85]:
# Cómo extraer una columna en particular de una matriz 1D de tuplas
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)
print(iris_1d.shape)

species = np.array([row[4] for row in iris_1d])
species[:5]

(150, 5)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [88]:
# Cómo convertir una matriz 1d de tuplas a una matriz 2d numpy
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4])

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

[[b'5.1' b'3.5' b'1.4' b'0.2']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']
 [b'4.6' b'3.1' b'1.5' b'0.2']]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [89]:
# Cómo calcular la media, mediana, desviación estándar de una matriz numpy
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [90]:
# Cómo normalizar una matriz para que los valores oscilen exactamente entre 0 y 1
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)

S = (sepallength - Smin)/sepallength.ptp()
print(S)

[0.222222 0.166667 0.111111 ... 0.611111 0.527778 0.444444]


In [97]:
# Cómo calcular la puntuación softmax
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])
print(sepallength)

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[5.1 4.9 4.7 ... 6.5 6.2 5.9]
[0.06081  0.049787 0.040762 ... 0.246597 0.182684 0.135335]
[0.00222  0.001817 0.001488 ... 0.009001 0.006668 0.00494 ]


In [102]:
#La función NumPy percentile()en Python se usa para calcular el percentil n de los 
# elementos de la matriz a lo largo del eje especificado. Básicamente usamos el 
# percentil en las estadísticas, lo que le da un número que describe el valor que
# un porcentaje dado de los valores es menor que.

    #numpy.percentile(arr, percentile, axis=None, out=None, overwrite_input=False, keepdims=False)
"""
    arr -array_like, esta es la matriz u objeto de entrada que se puede convertir en una matriz.
    
    percentile– array_like de float Percentil o secuencia de percentiles a calcular, 
    que debe estar entre 0 y 100 inclusive.
    
    axis– Eje o ejes a lo largo de los cuales se calcula el percentil.
    De forma predeterminada, se utiliza una matriz aplanada. axis = 0 
    significa a lo largo de la columna y axis = 1 significa trabajar a 
    lo largo de la fila.
    
    out – Una matriz de salida alternativa donde puede colocar el resultado.
    
    overwrite_input– Si el valor booleano es True, puede modificar la matriz
    de entrada mediante cálculos intermedios para ahorrar memoria.
    
    keepdims– El valor se establece en True, crea ejes reducidos con dimensiones
    de un tamaño.
"""
arr = np.array([2, 3, 5, 8, 9,4])

print("*"*20+" SOLUCIÓN "+"*"*20)
arr2 = np.percentile(arr, 50)
print(arr2)

print("*"*20+" SOLUCIÓN "+"*"*20)
arr2 = np.percentile(arr, 75)
print(arr2)

print("*"*20+" SOLUCIÓN "+"*"*20)
arr = np.array([[6, 8, 4],[ 9, 5, 7]])
arr2 = np.percentile(arr, 50)
print(arr2)

# Obtenga el percentil a lo largo del eje
arr2 = np.percentile(arr, 75, axis=0)
print(arr2)
arr2 = np.percentile(arr, 75, axis=1)
print(arr2)

******************** SOLUCIÓN ********************
4.5
******************** SOLUCIÓN ********************
7.25
******************** SOLUCIÓN ********************
6.5
[8.25 7.25 6.25]
[7. 8.]


In [98]:
# Cómo encontrar los puntajes de percentil de una matriz numpy
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])